### ISSUE TITLE
feature: 查询最新价格的函数

### ISSUE THREAD

**Issue by edwardsun** [haifengat/hf_ctp_py_proxy#11]
您好，
我想请问一下，有没有可能在行情类里添加询价函数
我想查询特定合约的最新价格
我google了一下，应该是ReqForQuoteInsert
阻塞式的查询价格使用起来应该会比较方便一些。
如果能添加到CTPQuote类里就好了。

谢谢

**Comment by haifengat** [comment]
这个是交易接口的函数,不能修改.
